name: q-and-a
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ant1441/do-app-rust-q-and-a
  name: q-and-a
  protocol: HTTP2
databases:
  - name: q-and-a-db
    engine: PG
    production: false
